### ISSUE TITLE
random UTF-8-MAC failures

### ISSUE THREAD

**Issue by beckermr** [conda-forge/libiconv-feedstock#39]
Following up on this thread (https://github.com/conda-forge/git-feedstock/issues/50).

We should either package a patch from this project

https://github.com/fumiyas/libiconv-utf8mac 

or build this project as the libiconv on osx.

**Comment by beckermr** [comment]
cc @conda-forge/core any thoughts here?

**Comment by jakirkham** [comment]
Has this been reported upstream? If so, are there patches upstream that could be used?

**Comment by beckermr** [comment]
Yes please read the associated issue in the GitHub feedstock. The upstream devs refuse to incorporate the apple encoding.

**Comment by hmaarrfk** [comment]
see https://github.com/conda-forge/git-feedstock/issues/50#issuecomment-624852740

but I don't really understand what UTF-8"-MAC" is? isn't UTF-8 a deterministic encoding of strings? what changes with UTF-8"-MAC"?

**Comment by beckermr** [comment]
IDK what changes either, but they are different.

**Comment by mbargull** [comment]
> isn't UTF-8 a deterministic encoding of strings?

The same Unicode string can be represented in different ways.
There different normalizations: https://en.wikipedia.org/wiki/Unicode_normalisation#Normalization

----
It's always a good thing to look out for what other distributors to.
For Linux I usually refer to Fedora/Debian/Arch's work.
For macOS it's usually Homebrew.

Homebrew has https://github.com/Homebrew/homebrew-core/blob/9911c3276bcc2a8f2e8a8359370c217e43cd8104/Formula/lib/libiconv.rb#L26 which is https://github.com/Homebrew/formula-patches/blob/9be2793af22750a2d1d053af0a9e2257d4ce7f4e/libiconv/patch-utf8mac.diff from 2015 -- i.e., a very low-maintenance patch.
I `diff`'ed https://github.com/fumiyas/libiconv-utf8mac against upstream and it is essentially the exact same patch.

It's probably reasonable for us to just apply that patch here on `osx-*` targets.

(N.B.: I'm not a Mac dev or user, so this is only an "outsider" assessment.)

**Comment by beckermr** [comment]
I think carrying that patch would be fine.

**Comment by jakirkham** [comment]
Yeah patching the existing package would be my preference as well
